# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oyQCitM_ifJQgcvZ9KmtPZSzYxxkYJXg
"""

#Library yang digunakan
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

#Mengambil data dari google drive
path_dataset = "/content/drive/MyDrive/ITTS Pelatihan Data/hotel_bookings 2.csv"

#Mengatur dataset yang akan digunakan
df= pd.read_csv(path_dataset)

#Mengecek dataset setelah diatur
df.head()

#Menampilkan jumlah baris dan jumlah kolom dari data yang digunakan
df.shape

#Menampilkan nama-nama kolom
df.columns

#Melihat tipe data dari tiap kolom
df.info()

#Mengonversi tipe data baris 'reservation_status_date' menjadi datetime
df['reservation_status_date'] =pd.to_datetime(df['reservation_status_date'])

df.info()

#Menghitung jumlah nilai null di setiap kolom
df.isnull().sum()

#Menghapus kolom-kolom yang memiliki nilai null
df.drop(['company','agent'], axis = 1, inplace=True)
df.dropna(inplace=True)

##Menghitung jumlah nilai null di setiap kolom kembali
df.isnull().sum()

df.describe()

#Mencari outliers
df['adr'].plot(kind='box')

#Membatasi data yang digunakan
df=df[df['adr']<5000]

#Menampilkan grafik jumlah status reservasi
canceled_perc = df['is_canceled'].value_counts(normalize=True)
print(canceled_perc)

plt.figure(figsize=(5,4))
plt.title(
    'Jumlah Status Reservasi'
)
plt.bar(['Not canceled', 'canceled'], df['is_canceled'].value_counts(), edgecolor='k', width=0.5)
plt.show()

#Menampilkan grafik dari status reservasi hotel yang berbeda
plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel', hue='is_canceled', data=df, palette ='Blues')
legend_labels,_= ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))

plt.title('status reservasi di tiap jenis hotel', size=20)
plt.xlabel('hotel')
plt.ylabel('jumlah reservasi')
plt.legend(['not canceled', 'canceled'])
plt.show()

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

#Mengambil rerata 'adr' dari tiap hotel
resort_hotel=resort_hotel.groupby('reservation_status_date')[['adr']].mean()
city_hotel=city_hotel.groupby('reservation_status_date')[['adr']].mean()

#Membuat grafik rerata 'adr' dalam plot
plt.figure(figsize =(20,8))
plt.title('Rerata pendapatan harian sewa kamar City Hotel and Resort Hotel', size=20)
plt.plot(resort_hotel.index, resort_hotel['adr'],label='Resort Hotel')
plt.plot(city_hotel.index, city_hotel['adr'],label='City Hotel')
plt.legend(fontsize=20)
plt.show()

df['month'] = df['reservation_status_date'].dt.month
plt.figure(figsize =(16,8))
ax1 = sns.countplot(x='month', hue='is_canceled', data=df, palette ='pastel')
legend_labels,_ =ax1. get_legend_handles_labels()
ax1.legend(bbox_to_anchor=(1,1))
plt.title('Status reservasi per bulan', size = 20)
plt.xlabel('month')
plt.ylabel('Jumlah reservasi')
plt.legend(['not canceled', 'canceled'])
plt.show()

plt.figure(figsize =(15,8))
plt.title('Rerata pendapatan harian sewa kamar perbulan', fontsize=30)
sns.barplot(x='month', y='adr', data = df[df['is_canceled'] == 1].groupby('month')[['adr']].sum().reset_index())
plt.show()

canceled_data=df[df['is_canceled']==1]
top_10_country =canceled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title('Top 10 negara dengan pembatalan reservasi')
plt.pie(top_10_country, autopct='%.2f', labels=top_10_country.index)

#Nama : Muhammad Kevin Hardiansyah
#Kelas : Free ITTS DS